# Generated by Django 5.2.12 on 2026-03-04 10:14

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GLEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gl_code', models.CharField(max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('FUZZY', 'Fuzzy')], max_length=10)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('matched_on', models.JSONField(default=list)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.banktransaction')),
                ('gl_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.glentry')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reconciliation.reconciliationjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='glentry',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_entries', to='reconciliation.reconciliationjob'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='reconciliation.reconciliationjob'),
        ),
        migrations.AddIndex(
            model_name='glentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='gl_entry_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='bank_tx_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('job', 'external_id'), name='unique_bank_tx_per_job'),
        ),
    ]
